apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: logs
  namespace: helved
  labels:
    apiserver-access: "enabled"
spec:
  liveness:
    path: /
  readiness:
    path: /
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 20m
      memory: 24Mi
    limits:
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: hooks.slack.com
          ports:
            - port: 443
  envFrom:
    - secret: slack-webhook

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logs-role
  namespace: helved
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logs-role-binding
  namespace: helved
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logs-role
subjects:
  - kind: ServiceAccount
    name: logs

